### ISSUE TITLE
prettify bench::mark output?

### ISSUE THREAD

**Issue by bbolker** [MayaGans/RInfernotes#2]
I made a "setup" chunk (with `message=FALSE, echo=FALSE`) that defines this function:
```
library(tidyverse)
test <- function(...) {
    knitr::kable(format="html",
                 bench::mark(...)
                 %>% transmute(expression,
                               median,
                               relative_time=round(c(median/min(median)),1))
                 %>% arrange(relative_time)
                 
    ) %>% kableExtra::kable_styling(font_size = 16)
}
```

then I replaced `bench::mark(<stuff>)[<stuff>]` with `test(<stuff>)` and put it in a separate chunk with `results="asis"`.

- **pro**: prettier.  Shows the stuff I care most about (median time, relative time)
- **con**:  more magical (the current version can be run exactly as is)

**Comment by MayaGans** [comment]
oooh I love this!!! adding now 😄 

<img width="587" alt="Screen Shot 2020-09-08 at 5 18 28 PM" src="https://user-images.githubusercontent.com/6053906/92539893-c73b7480-f1f7-11ea-80ab-6140905bd3d5.png">
